
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Kevin Wong
tagline: iOS Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kevin.wl.02@gmail.com
website: kevinwl02.github.io #do not add http://
linkedin: kevin-wong-251a8134
github: kevinwl02
twitter: '@kevinwl02'
